### ISSUE TITLE
Use Optitrack as motion capture type?

### ISSUE THREAD

**Issue by cbDragon** [OPT4SMART/crazychoir#10]
Great appreciation to your great work! This simulation environment really help our experiment a lot! But I still have a few questions, and it will be great if you can provide some solution:

Our motion capture type is Optitrack, it also has the SDK interface. How could I switch the Vicon's API into Optitrack's? Does it will need a lot of work?

**Comment by andrea-testa** [comment]
We appreciate your interest in our toolbox!
Since we do not have an Optitrack system, we only provided an interface to Vicon. I will explain how we did, so you can eventually modify it accordingly.

First, we created a bridge that reads Vicon data using Vicon SDK and sends it over ROS 2. You can find it at the following link

https://github.com/OPT4SMART/ros2-vicon-receiver

Then, we created a function that subscribes to the Vicon topic and puts the odometry data into a proper structure

https://github.com/OPT4SMART/ChoiRbot/blob/master/choirbot/choirbot/utils/position_getter.py

Specifically, you can create your own 'handler' in the 'pose_subscribe' function. We already created two handlers to manage data coming from our Vicon bridge as 'Position messages' and generic data coming as 'Odometry' messages (e.g., from Gazebo and Webots).   You can then mimic what we did in the 'vicon_callback' function.

Let us know if you have any doubts and we will support you!

**Comment by cbDragon** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by andrea-testa** [comment]
Great! Keep us updated for any issue!
